name: "Deploy" # This is the name of the workflow

on: # This is the trigger for the workflow
  push: # This is the trigger for the workflow
    branches: [main] # This is the branch that the workflow will run on
    paths-ignore: # This is the paths that the workflow will ignore
      - "./github/workflows/**/**"
      - "README.md"

  workflow_dispatch: # Manually trigger the workflow

jobs: # This is the list of jobs that will be run
  test:
    runs-on: ubuntu-latest # This is the OS that the workflow will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This is the action that will be run

      - name: Caching Dependencies
        uses: actions/cache@v4 # This is the action that will be run
        with: # This is the options for the action
          path: ~/.npm # This is the path to the directory that will be cached
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} #
          run: echo "Caching dependencies..."

      - name: Install Nodejs
        uses: actions/setup-node@v4 # This is the action that will be run
        with: # This is the options for the action
          node-version: "20" # This is the version of Node that will be installed

      # - name: Node version
      #   run: node -v # This is the command that will be run

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: |
          npm run test
          echo "Tests passed!"

  deploy: # This is the name of the job
    needs: test # If this job needs another job to run, this is the job that will run first
    runs-on: ubuntu-latest # This is the OS that the workflow will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This is the action that will be run

      - name: Caching Dependencies
        uses: actions/cache@v4 # This is the action that will be run
        with: # This is the options for the action
          path: ~/.npm # This is the path to the directory that will be cached
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # This is the key for the cache

      - name: Install Nodejs
        uses: actions/setup-node@v4 # This is the action that will be run
        with: # This is the options for the action
          node-version: "20" # This is the version of Node that will be installed

      # - name: Node version
      #   run: node -v # This is the command that will be run

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          echo "Deploying to production"
          echo "Deployed successfully!"
