name: "Deploy" # This is the name of the workflow

on: # This is the trigger for the workflow
  - push # This is the trigger for the workflow
  - workflow_dispatch # Manually trigger the workflow

jobs: # This is the list of jobs that will be run
  deploy: # This is the name of the job
    runs-on: ubuntu-latest # This is the OS that the workflow will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This is the action that will be run
      
      - name: Install Nodejs
        uses: actions/setup-node@v4 # This is the action that will be run
        with: # This is the options for the action
          node-version: '20' # This is the version of Node that will be installed
          cache: 'npm'
        
      - name: Node version
        run: node -v # This is the command that will be run
      
      - name: Install Dependencies
        run: npm ci 
      
      # - name: Build
      #   run: npm run build
      
      - name: Deploy
        run: |
          echo "Deploying to production"
          npm run dev 


