name: "Deploy App" # This is the name of the workflow

on: # This is the trigger for the workflow
  push: # This is the trigger for the workflow
    branches: [main] # This is the branch that the workflow will run on
    
  workflow_dispatch: # Manually trigger the workflow

jobs: # This is the list of jobs that will be run
  test:
    runs-on: ubuntu-latest # This is the OS that the workflow will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This is the action that will be run

      - name: Caching Dependencies
        uses: actions/cache@v4 # This is the action that will be run
        with: # This is the options for the action
          path: ~/.npm # This is the path to the directory that will be cached
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} #

      - name: Install Nodejs
        uses: actions/setup-node@v4 # This is the action that will be run
        with: # This is the options for the action
          node-version: "20" # This is the version of Node that will be installed

      # - name: Node version
      #   run: node -v # This is the command that will be run

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: |
          npm run test
          echo "Tests passed!"

  build:
    needs: test # If this job needs another job to run, this is the job that will run first
    runs-on: ubuntu-latest # This is the OS that the workflow will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This is the action that will be run

      - name: Caching Dependencies
        uses: actions/cache@v4 # This is the action that will be run
        with: # This is the options for the action
          path: ~/.npm # This is the path to the directory that will be cached
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # This is the key for the cache

      - name: Install Nodejs
        uses: actions/setup-node@v4 # This is the action that will be run
        with: # This is the options for the action
          node-version: "20" # This is the version of Node that will be installed

      # - name: Node version
      #   run: node -v # This is the command that will be run

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          echo "Build successful!"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3 # This is the action that will be run
        with: # This is the options for the action
          name: github-pages # This is the name of the artifact
          path: dist # This is the path to the artifact

  deploy: # This is the name of the job
    needs:
      build # If this job needs another job to run, this is the job that will run first


      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

      # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This is the token that will be used to deploy to GitHub Pages
          publish_dir: dist # This is the directory that will be deployed
